version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:7
    container_name: mae-eliot-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mae_eliot
    networks:
      - mae-eliot-network

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: mae-eliot-backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=mae_eliot
      - SECRET_KEY=CHANGEZ_CETTE_CLE_SECRETE_MAINTENANT_123456789
    depends_on:
      - mongodb
    networks:
      - mae-eliot-network

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8001
    container_name: mae-eliot-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mae-eliot-network

volumes:
  mongodb_data:
    driver: local

networks:
  mae-eliot-network:
    driver: bridge